mod browser;
mod browser_context;
mod cdp;
pub mod chromatica;
mod element;
mod http_request;
mod http_response;
mod iframe;
mod js_dialogs;
pub mod page;
pub use cdp::domains::emulation::{UserAgentBrandVersion, UserAgentMetadata};
pub use cdp::domains::page::PrintToPDF;
pub use cdp::emulation_manager::UserAgentOverride;
